import "./Features.css";

const features = [
  {
    icon: "🤖",
    title: "AI Interview",
    description: "Practice with role-specific questions generated by AI.",
  },
  {
    icon: "📄",
    title: "Resume Analysis",
    description: "Discover strengths and gaps before your next interview.",
  },
  {
    icon: "📊",
    title: "Performance Dashboard",
    description: "Track your progress and see exactly where to improve.",
  },
  {
    icon: "🎤",
    title: "Voice Interview",
    description: "Build confidence through realistic spoken interviews.",
    comingSoon: true,
  },
];

function Features() {
  return (
    <section className="features" id="features">
      <div className="features-heading">
        <span className="features-label">Everything you need</span>
        <h2>Prepare for every part of the interview</h2>
        <p>
          One focused workspace to practice, measure your progress, and become
          a stronger candidate.
        </p>
      </div>

      <div className="features-grid">
        {features.map((feature) => (
          <article className="feature-card" key={feature.title}>
            <div className="feature-card-top">
              <span className="feature-icon" aria-hidden="true">
                {feature.icon}
              </span>

              {feature.comingSoon && (
                <span className="coming-soon">Coming soon</span>
              )}
            </div>

            <h3>{feature.title}</h3>
            <p>{feature.description}</p>
          </article>
        ))}
      </div>
    </section>
  );
}

export default Features;